### ISSUE TITLE
It does not compile at all!

### ISSUE THREAD

**Issue by shinybean** [Panquesito7/tic-tac-toe#2]
It is a bit of haywire; nearly everything seems to be dysfunctional. I did what your guide wrote; copy the header and code file into my proj/proj and compiled them and ran and was presented with heaps of errors.

**Comment by Panquesito7** [comment]
Can you try to follow the steps [**mentioned here**](https://dev.to/panquesito7/how-to-create-a-tic-tac-toe-game-in-cli-c-in-windows-3l9g) and see if it works? Also, what is your OS? Make sure you're on Windows. Thanks. 🙂

**Comment by Panquesito7** [comment]
This should not happen as soon as #7 is fixed.
